parameters:
    database_driver: pdo_mysql
    database_host: localhost
    database_port: null
    database_name: portfolio
    database_user: root
    database_password: null
    mailer_transport: smtp
    mailer_host: localhost
    mailer_user: null
    mailer_password: null
    locale: en
    secret: thisIsNotASecretChangeMe
    database_path: null
    assetic.filter.compass.images_dir: %kernel.root_dir%/../web/images
    assetic.filter.compass.generated_images_path: %kernel.root_dir%/../web/generated/images
    assetic.filter.compass.http_path: /generated